# Generated by Django 5.1.6 on 2025-04-13 09:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancel_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
